os:
  - linux
language: c
compiler:
  - gcc
  - clang
env:
  - COMPILE=true
  - COMPILE=false
branches:
  only:
    - master
addons:
  apt_packages:
    - libgmp3-dev
script:
  - sh scripts/travis_build.sh
  - gapsrc/bin/gap.sh tst/testall.g

