os:
  - linux
language: c
compiler:
  - gcc
  - clang
branches:
  only:
    - master
addons:
  apt_packages:
    - libgmp3-dev
script:
  - cd ..
  - git clone --depth=50 https://github.com/gap-system/gap.git gap
  - cd gap
  - ./configure --with-gmp=system
  - make
  - make bootstrap-pkg-minimal
  - cd pkg
  - ln -s ../../datastructures .
  - cd datastructures
  - ./autogen.sh
  - ./configure
  - make
  - cd ../..
  - echo "Test(\"pkg/datastructures/tst/testall.tst\"); quit;" | sh bin/gap.sh | tee testlog.txt | grep --colour=always -E "########> Diff|$"
  - ( ! grep "########> Diff" testlog.txt )

