os:
  - linux
language: c
compiler:
  - gcc
  - clang
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgmp3-dev
script:
  - cd ..
  - git clone --depth=50 https://github.com/gap-system/gap.git gap
  - cd gap
  - ./configure --with-gmp=system
  - make
  - mkdir pkg
  - cd pkg
  - wget ftp://ftp.gap-system.org/pub/gap/gap47/tar.gz/packages/GAPDoc-1.5.1.tar.gz
  - tar xvzf GAPDoc-1.5.1.tar.gz
  - ln -s ../../datastructures .
  - cd datastructures 
  - ./autogen.sh
  - ./configure
  - make
  - cd ../..
  - echo "Read(\"pkg/datastructures/tst/testall.g\"); quit;" | sh bin/gap.sh
