os:
  - linux
language: c
compiler:
  - gcc
  - clang
env:
  - COMPILE=true
  - COMPILE=false
branches:
  only:
    - master
addons:
  apt_packages:
    - libgmp3-dev
script:
  - cd ..
  - git clone --depth=50 https://github.com/gap-system/gap.git gap
  - cd gap
  - ./configure --with-gmp=system
  - make
  - make bootstrap-pkg-minimal
  - cd pkg
  - ln -s ../../datastructures .
  - cd datastructures
  - ./autogen.sh
  - ./configure
  - if [ $COMPILE = true ]; then make; fi
  - cd ../..
  - echo "Read(\"pkg/datastructures/tst/testall.g\"); quit;" | sh bin/gap.sh
