dist: trusty
language: c
os:
  - linux
compiler:
  - gcc
  - clang
env:
  - COMPILE=true
branches:
  only:
    - master
addons:
  apt_packages:
    - libgmp3-dev
script:
  - sh scripts/travis_build.sh
  - gapsrc/bin/gap.sh tst/testall.g

